# thaw_config.ini
#
# Copyright (C) 2011-2019 Vas Vasiliadis
# University of Chicago
#
# Results thawing utility configuration
#
##

# AWS general settings
[aws]
AwsRegionName = us-east-1

# S3 settings
[s3]
ResultsBucket = mpcs-cc-gas-results

# Glacier settings
[glacier]
VaultName = mpcs-cc

# DynamoDB settings
[dynamodb]
AnnotationsTable = peilij_annotations

# SQS settings
[sqs]
ThawQueue = peilij_thaw_queue
WaitTimeSeconds = 20
MaxNumberOfMessages = 10

# Thaw settings
[thaw]
CheckIntervalSeconds = 300

### EOF