# ann_config.ini
#
# Annotator configuration
#
##

# AWS general settings
[aws]
AwsRegionName = us-east-1

# S3 settings
[s3]
InputsBucket = mpcs-cc-gas-inputs
ResultsBucket = mpcs-cc-gas-results

# DynamoDB settings
[dynamodb]
AnnotationsTable = peilij_annotations

# SQS settings
[sqs]
JobRequestsQueue = peilij_job_requests
WaitTimeSeconds = 20
MaxNumberOfMessages = 1

# SNS settings
[sns]
JobResultsTopic = peilij_job_results
ArchiveTopic = peilij_archive_topic

### EOF