# restore_config.ini
#
# Copyright (C) 2011-2019 Vas Vasiliadis
# University of Chicago
#
# Results restore utility configuration
#
##

# AWS general settings
[aws]
AwsRegionName = us-east-1

# Glacier settings
[glacier]
VaultName = mpcs-cc

# DynamoDB settings
[dynamodb]
AnnotationsTable = peilij_annotations

# SQS settings
[sqs]
RestoreQueue = peilij_restore_queue
ThawQueue = peilij_thaw_queue
WaitTimeSeconds = 20
MaxNumberOfMessages = 10

# SNS settings
[sns]
ThawTopic = peilij_thaw_topic

### EOF