# archive_config.ini
#
# Copyright (C) 2011-2019 Vas Vasiliadis
# University of Chicago
#
# Results archive utility configuration
#
##

# AWS general settings
[aws]
AwsRegionName = us-east-1

# S3 settings
[s3]
ResultsBucket = mpcs-cc-gas-results

# DynamoDB settings
[dynamodb]
AnnotationsTable = peilij_annotations

# Glacier settings
[glacier]
VaultName = mpcs-cc

# SQS settings
[sqs]
ArchiveQueue = peilij_archive_queue
WaitTimeSeconds = 20
MaxNumberOfMessages = 10

# SNS settings
[sns]
ArchiveTopic = peilij_archive_topic

# Archive settings
[archive]
DelaySeconds = 300

### EOF